config/routes.rb
Rails.application.routes.draw do
  get 'hashtags/:hashtag', to: 'hashtags#show',      as: :hashtag

  resources :videos, only: [:index, :show, :new, :create, :destroy] do
    get 'filter/:name' => 'videos#filter', on: :collection
  end
  resources :posts do
    resources :comments
  end
  resources :comments, only: [:index, :create] do
    member do
      post :like, :unlike
    end
  end
  get '/posts/(:post_id)/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/user/:user', to: 'posts#user_index', as: :user_index
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:index, :show]

  root 'page#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  acts_as_likeable
  acts_as_tree order: 'created_at DESC', dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :destroy, :like, :unlike]
  # load_and_authorize_resource

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new(parent_id: params[:parent_id])
    @post = Post.find(params[:post_id])
  end

  def edit
  end

  def create
    @post = Post.find(params[:post_id])

    if params[:comment][:parent_id].to_i > 0
      parent = @post.comments.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
      @comment.post_id = @post.id
    else
      @comment = @post.comments.new(comment_params)
    end

    @comment.user_id = current_user.id

    @comment.save
    flash[:default] = 'Comment was successfully created.'
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment.destroy
    flash[:default] = 'Comment was successfully destroyed.'
    redirect_to @post
  end

  def like
    current_user.like!(@comment)
    redirect_to @comment.post
  end

  def unlike
    current_user.unlike!(@comment)
    redirect_to @comment.post
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments)
    comments.map do |comment, nested_comments|
      render(comment) +
        (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments), class: 'replies') : nil)
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
    <p>
      <strong>
        Posted <%= time_ago_in_words(comment.created_at, include_seconds: true) %> ago by <%= User.find(comment.user_id).email %>
      </strong>
      <% if user_signed_in?  %>
      	<% if  current_user.likes?(comment) %>
      		<%= link_to('Unlike', unlike_comment_path(comment), method: :post) %>
      	<% else %>
      		<%= link_to('Like', like_comment_path(comment), method: :post) %>
      	<% end %>
      <% end %>

      <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
      <%= comment.likers_count %>

      <% if can? :destroy, comment %>
        <%= link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs"  %>
      <% end %>

      <!--<br/>-->
      <blockquote><%= comment.body %></blockquote>

      <% if user_signed_in? && comment.root? %>
        <% from_reply_form ||= nil %>
        <% unless from_reply_form %>
          <p><%= link_to 'reply', new_comment_path(@post, comment.id) %></p>
        <% end %>
      <% end %>
    </p> <!--extra closing tab????-->
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
    <%= f.hidden_field :parent_id %>
    <div class="form-group">
      <%= f.label :body, "New comment" %><br/>
      <%= f.text_area :body, placeholder: 'Write a comment...', class: 'form-control', required: true %>
    </div>
    <div class="actions">
      <%= f.submit "Add comment", class: 'btn btn-primary' %>
    </div>
<% end %>

<br>

app/views/comments/new.html.erb
<h1>Reply</h1>

<% if @comment.parent %>
    <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>