config/routes.rb
Rails.application.routes.draw do
  get 'hashtags/:hashtag', to: 'hashtags#show',      as: :hashtag

  resources :videos, only: [:index, :show, :new, :create, :destroy] do
    get 'filter/:name' => 'videos#filter', on: :collection
  end
  resources :posts do
    resources :comments
  end
  resources :comments, only: [:index, :create] do
    member do
      post :like, :unlike
    end
  end
  get '/posts/(:post_id)/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/user/:user', to: 'posts#user_index', as: :user_index
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:index, :show]

  root 'page#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include SimpleHashtag::Hashtaggable
  hashtaggable_attribute :description

  belongs_to :user
  has_one :video, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :video

  validates_presence_of :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('updated_at DESC')
    @posts = @posts.select { |p| p.title.include?(params[:title]) } unless params[:title].nil?
    @posts = @posts.select { |p| User.find(p.user_id).email.include?(params[:author]) } unless params[:author].nil?
    @posts = @posts.select { |p| p.description.include?(params[:description]) } unless params[:description].nil?
    order = if params[:order] == 'descending'
              ' DESC'
            else
              ' ASC'
            end

    if params[:sort_option].present?
      if params[:sort_option] == 'user'
        @posts = Post.all.order('user_id' + order) unless params[:sort_option].empty?
      else
        @posts = Post.all.order(params[:sort_option].to_s + order) unless params[:sort_option].empty?
      end
    end

    @listing = Post.new.attributes.keys[1..5]
    @listing[2] = @listing[2][0..3]

    @hashtags = SimpleHashtag::Hashtag.select { |hashtag| !hashtag.hashtaggables.empty? }
  end

  def user_index
    @posts = current_user.posts
    @listing = Post.new.attributes.keys[1..5]
    @listing[2] = @listing[2][0..3]
    @hashtags = SimpleHashtag::Hashtag.select { |hashtag| !hashtag.hashtaggables.empty? }

    render :index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.hash_tree
  end

  # GET /posts/new
  def new
    @post = Post.new
    @video = @post.build_video
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      flash[:default] = 'Post was successfully created.'
      redirect_to @post
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      flash[:default] = 'Post was successfully updated.'
      redirect_to @post
    else
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    flash[:default] = 'Post was successfully destroyed.'
    redirect_to posts_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :description, video_attributes: [:link])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>-->
      <div class="alert alert-alert">
        <ul>
          <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Set a title', class: 'form-control' %>
  </div>
  <br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: 'Write a description and don\'t forget to include a #hashtag :-)', class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= f.fields_for :video do |ff| %>
        <div class="form-group">
          <%= ff.label :video_link %>
          <%= ff.text_field :link, placeholder: 'Add a video link', class: 'form-control' %>
        </div>
    <% end %>
  </div>
  <div class="actions">
    <%= link_to 'Back', posts_path, class: 'btn btn-default' %>
    <%= f.submit nil, class: 'btn btn-success'%>
  </div>
<% end %>

<br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="text-center panel-title" title="Hashtags">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse_hashtags">
          Find post by hashtags included in description
        </a>
      </h1>
    </div>
    <div id="collapse_hashtags" class="panel-collapse collapse in">
      <div class="panel-body">
        <ul class="nav nav-pills text-center" role="tablist">
          <% @hashtags.each do |hashtag| %>
            <%= link_to hashtag.name, hashtag_path(hashtag.name), :class => 'btn btn-default' %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="text-center panel-title" title="Searching & sorting options">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse_sas">
          Searching and sorting options
        </a>
      </h1>
    </div>
    <div id="collapse_sas" class="panel-collapse collapse">
      <div class="panel-body">
        <table>
          <tr>
            <td>
              <div>
                <p>
                <h3 class="text-center"> Search by title:</h3></p>
                <!-- When submit the form, the view rendered will be the index view of our articles resource -->
                <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                    <div>
                      <center>
                        <%= text_field_tag :title, params[:title], class: "span2" %>
                        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
                         of using a Rails form helper -->
                        <button class="btn" type="submit">Search</button>
                      </center>
                    </div>
                <% end %>
                <%= yield %>
              </div>
            </td>

            <td>
              <div>
                <p>
                <h3 class="text-center"> Search by author:</h3></p>
                <!-- When submit the form, the view rendered will be the index view of our articles resource -->
                <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                    <div>
                      <center>
                        <%= text_field_tag :author, params[:author], class: "span2" %>
                        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
                             of using a Rails form helper -->
                        <button class="btn" type="submit">Search</button>
                      </center>
                    </div>
                <% end %>
                <%= yield %>
              </div>
            </td>

            <td>
              <div>
                <p>
                <h3 class="text-center"> Search by description:</h3></p>
                <!-- When submit the form, the view rendered will be the index view of our articles resource -->
                <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                    <div>
                      <center>
                        <%= text_field_tag :description, params[:description], class: "span2" %>
                        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
                             of using a Rails form helper -->
                        <button class="btn" type="submit">Search</button>
                      </center>
                    </div>
                <% end %>
                <%= yield %>
              </div>
            </td>
            <td>
              <div>
                <p>
                <h3 class="text-center"> Sort by:</h3></p>
                <%= form_tag(posts_path, :method => "get", class: "navbar-form", id: "search-form") do %>
                    <div>
                      <center>
                        <%= select_tag :sort_option, options_for_select(@listing.each), include_blank: true, class: "span2" %>
                        <%= select_tag :order, options_for_select(['descending', 'ascending']), class: "span2" %>
                        <button class="btn" type="submit">Sort</button>
                      </center>
                    </div>
                <% end %>
                <%= yield %>
              </div>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

<div align="right">
  <% if user_signed_in? %>
    <% if can? :create, Post %>
      <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

</br>
</br>

<table class="table table-striped">
  <tbody>
  <% @posts.each do |post| %>

      <tr>
        <td>
          <!--
          <div class="yt_video thumbnail">
            <%= link_to image_tag("https://img.youtube.com/vi/#{post.video.uid}/mqdefault.jpg", alt: post.video.title,
                                  class: 'img-rounded'),
                        "https://www.youtube.com/watch?v=#{post.video.uid}", target: '_blank' %>
          </div>
          -->
          <iframe width="280" height="157" src="https://www.youtube.com/embed/<%= post.video.uid %>" frameborder="0" allowfullscreen></iframe>
        </td>
        <td align="left">

          <BR/>
          <BR/>

          <div>
            <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
            <%= post.video.like_count %>
          </div>
          <div>
            <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
            <%= post.video.dislike_count %>
          </div>
          <div>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            <%= post.video.view_count %>
          </div>
          <BR/>
          <div><%= link_to '', post_path(post, :anchor => "comments"), class: "btn btn-default glyphicon glyphicon-comment" %></div>
        </td>
        <td align="center">
          <div class="post-title">
            <h1><%= post.title %> </h1>
          </div>
          <div class="post-video-title">
            <b> <%= post.video.title %> </b>
          </div>
          <div class="post-description" vertical-align="middle">
            <%= linkify_hashtags post.description %>
          </div>
          <div class="post-author">
            <h5>Posted by <%= User.find(post.user_id).email %></h5>
          </div>
        </td>

        <td align="center">
          <div><%= link_to 'Show', post, class: "btn btn-default" %></div>
          </br>
          <div>
            <% if can? :update, post %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
            <% end %>
          </div>
          </br>
          <div>
            <% if can? :destroy, post %>
              <%= link_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-default" %>
            <% end %>
          </div>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="page-header text-center">
  <h1><%= @post.title %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="text-center">
      <iframe width="1120" height="630" src="https://www.youtube.com/embed/<%= @post.video.uid %>" frameborder="0" allowfullscreen>
      </iframe>
    </div>
    <ul>
      <div class="text-right">
       <h5>Posted by: <strong><%= User.find(@post.user_id).email %></strong></h5>
      </div>
      <h4><strong>Description:</strong> <%= linkify_hashtags @post.description %></h4>
    </ul>

    <div class="panel panel-default bg-orange">
      <div class="panel-body">
        <ul>
          <div class="container-fluid">
          <div class="text-center">
            <h5><strong><%= link_to @post.video.title, @post.video.link %></strong></h5>
          </div>
            <div class="row padding-bottom">
              <div class="col-md-4">
                <strong>
                  Likes: <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                </strong> 
                <%= @post.video.like_count %>   
              </div>
              <div class="col-md-4">
                <strong>
                  Dislikes: <span class="glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
                </strong> 
                <%= @post.video.dislike_count %>
              </div>
              <div class="col-md-4">
                <strong>Views:</strong>
                <%= @post.video.view_count %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <strong>Published at:</strong> <%= @post.video.published_at %>
            </div>
            <div class="col-md-4">
              <strong>Category:</strong> <%= @post.video.category_title %>
            </div>
            <div class="col-md-4">
              <strong>Duration:</strong> <%= @post.video.duration %>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </div>

</div>

<div align="right">
  <% if can? :update, @post %>
      <%= link_to 'Edit', edit_post_path(@post) , class: 'btn btn-warning' %>
  <% end %>
  <% if can? :destroy, @post %>
      <%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  <% end %>
  <%= link_to 'Back', posts_path, class: 'btn btn-default' %>
</div>

</br>
<!--<h2>Comments</h2>-->
<div id="comments">
  <%= comments_tree_for @comments %>
</div>

<section>
  <a id="comments">
    <% if user_signed_in? %>
      <%= form_for [@post, Comment.new] do |f| %>
        <div class="form-group">
          <%= f.label :body, 'New comment' %><br/>
          <%= f.text_area :body, placeholder: 'Write a comment...', class: 'form-control', required: true %>
        </div>
        <div class="actions">
          <%= f.submit 'Add comment', class: 'btn btn-primary' %>
        </div>
      <% end %>
    <% end %>
  </a>
</section>

<br>