config/routes.rb
Rails.application.routes.draw do
  get 'hashtags/:hashtag', to: 'hashtags#show',      as: :hashtag

  resources :videos, only: [:index, :show, :new, :create, :destroy] do
    get 'filter/:name' => 'videos#filter', on: :collection
  end
  resources :posts do
    resources :comments
  end
  resources :comments, only: [:index, :create] do
    member do
      post :like, :unlike
    end
  end
  get '/posts/(:post_id)/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/posts/user/:user', to: 'posts#user_index', as: :user_index
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:index, :show]

  root 'page#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Video Blog App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>Video Blog App</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li <% if current_page?(posts_path) %> class='active' <% end %>>
          <a href=<%= posts_path %>>Posts</a>
        </li>
        <li <% if current_page?(videos_path) %> class='active' <% end %>>
          <a href=<%= videos_path %>>Videos</a>
        </li>
        <% if can? :manage, User %>
          <li <% if current_page?(users_path) %> class='active' <% end %>>
            <a href=<%= users_path %>>Users</a>
          </li>
        <% end %>
      </ul>
      <!--
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      -->
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong><%= current_user.email %></strong> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My profile', current_user %></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2), :class => 'navbar-link' %></li>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>